const facts = {

H: "Hydrogen is the lightest element and the most abundant element in the universe.",
He: "Helium is a noble gas and is commonly used in balloons and cooling systems.",
Li: "Lithium is a soft metal widely used in rechargeable batteries.",
Be: "Beryllium is a lightweight metal used in aerospace applications.",
B: "Boron is a metalloid used in glass, ceramics and detergents.",
C: "Carbon is the basis of organic chemistry and is found in all known living organisms.",
N: "Nitrogen makes up about 78% of Earth's atmosphere.",
O: "Oxygen is essential for respiration and makes up about 21% of Earth's atmosphere.",
F: "Fluorine is the most reactive and electronegative element.",
Ne: "Neon is a noble gas famous for its use in brightly glowing signs.",

Na: "Sodium is a highly reactive metal and is an important component of table salt.",
Mg: "Magnesium is a lightweight metal used in alloys and is important for living organisms.",
Al: "Aluminium is a lightweight metal widely used in transportation and construction.",
Si: "Silicon is important in electronics and is a major component of computer chips.",
P: "Phosphorus is important for DNA, bones and energy transfer in living organisms.",
S: "Sulfur is a yellow nonmetal used in fertilizers and sulfuric acid production.",
Cl: "Chlorine is used to disinfect drinking water and swimming pools.",
Ar: "Argon is a noble gas commonly used in welding and lighting.",

K: "Potassium is an important mineral for nerve and muscle function.",
Ca: "Calcium is essential for strong bones and teeth.",
Sc: "Scandium is a lightweight metal used in some aluminium alloys.",
Ti: "Titanium is strong, lightweight and highly resistant to corrosion.",
V: "Vanadium is mainly used to strengthen steel.",
Cr: "Chromium is responsible for the shiny finish of many stainless-steel objects.",
Mn: "Manganese is important in steel production and is also a trace nutrient.",
Fe: "Iron is an important metal used in construction and manufacturing.",
Co: "Cobalt is used in some rechargeable batteries and metal alloys.",
Ni: "Nickel is commonly used in stainless steel and corrosion-resistant alloys.",
Cu: "Copper is an excellent conductor of electricity and is widely used in wiring.",
Zn: "Zinc is used to protect iron and steel from corrosion through galvanization.",
Ga: "Gallium can melt in your hand because it has a very low melting point.",
Ge: "Germanium is a semiconductor used in electronics and optical devices.",
As: "Arsenic is a metalloid with uses in specialized materials and semiconductors.",
Se: "Selenium is a trace element needed in small amounts by the human body.",
Br: "Bromine is a reddish-brown liquid at room temperature.",
Kr: "Krypton is a noble gas used in some specialized lighting.",

Rb: "Rubidium is a very reactive alkali metal.",
Sr: "Strontium compounds can produce a bright red color in fireworks.",
Y: "Yttrium is used in some lasers, ceramics and superconducting materials.",
Zr: "Zirconium is highly resistant to corrosion and is used in nuclear applications.",
Nb: "Niobium is used to make strong steel alloys and superconducting materials.",
Mo: "Molybdenum has a very high melting point and is used in strong alloys.",
Tc: "Technetium was the first element to be produced artificially.",
Ru: "Ruthenium is a rare metal used in electronics and specialized alloys.",
Rh: "Rhodium is a rare metal used in catalytic converters.",
Pd: "Palladium is used in catalytic converters and electronics.",
Ag: "Silver has the highest electrical conductivity of any element.",
Cd: "Cadmium is a soft metal that has been used in batteries and pigments.",
In: "Indium is a soft metal used in touchscreens and semiconductors.",
Sn: "Tin is used to coat other metals and is an important component of solder.",
Sb: "Antimony is a metalloid used in flame retardants and alloys.",
Te: "Tellurium is a metalloid used in some solar cells.",
I: "Iodine is important for the production of thyroid hormones.",
Xe: "Xenon is a noble gas used in specialized lamps and some medical applications.",

Cs: "Caesium is an extremely reactive alkali metal.",
Ba: "Barium compounds are used in medical imaging and fireworks.",
La: "Lanthanum is used in camera lenses and some rechargeable batteries.",

Ce: "Cerium is the most abundant of the lanthanide elements.",
Pr: "Praseodymium is used in special glass and strong permanent magnets.",
Nd: "Neodymium is used to make very powerful permanent magnets.",
Pm: "Promethium is a radioactive lanthanide with no stable isotopes.",
Sm: "Samarium is used in powerful magnets and some specialized materials.",
Eu: "Europium is used to produce red colors in television and display screens.",
Gd: "Gadolinium is used as a contrast agent in some MRI scans.",
Tb: "Terbium is used in some green phosphors and electronic devices.",
Dy: "Dysprosium is used in powerful magnets that need to withstand high temperatures.",
Ho: "Holmium has one of the strongest magnetic properties of any element.",
Er: "Erbium is widely used in fiber-optic communication systems.",
Tm: "Thulium is the least abundant naturally occurring lanthanide.",
Yb: "Ytterbium is used in some lasers and specialized materials.",
Lu: "Lutetium is the densest and hardest of the lanthanides.",

Hf: "Hafnium is resistant to corrosion and has a high melting point.",
Ta: "Tantalum is highly corrosion-resistant and is used in electronic capacitors.",
W: "Tungsten has the highest melting point of all elements.",
Re: "Rhenium has one of the highest melting points of all elements.",
Os: "Osmium is one of the densest naturally occurring elements.",
Ir: "Iridium is extremely corrosion-resistant.",
Pt: "Platinum is a valuable metal widely used in catalysts and jewelry.",
Au: "Gold is highly unreactive and has been valued for thousands of years.",
Hg: "Mercury is a metal that is liquid at room temperature.",
Tl: "Thallium is a soft, heavy metal with limited specialized uses.",
Pb: "Lead is a dense metal historically used in batteries and radiation shielding.",
Bi: "Bismuth is a heavy metal with relatively low toxicity compared with many neighboring heavy metals.",
Po: "Polonium is a rare radioactive element.",
At: "Astatine is an extremely rare radioactive halogen.",
Rn: "Radon is a radioactive noble gas produced naturally from radioactive decay.",

Fr: "Francium is an extremely rare and highly radioactive alkali metal.",
Ra: "Radium is a radioactive alkaline-earth metal.",
Ac: "Actinium is a radioactive metal and gives its name to the actinide series.",

Th: "Thorium is a naturally occurring radioactive metal being studied as a potential nuclear fuel.",
Pa: "Protactinium is a rare radioactive element.",
U: "Uranium is a naturally occurring radioactive element used as nuclear fuel.",
Np: "Neptunium was the first transuranium element to be discovered.",
Pu: "Plutonium is a radioactive element used in specialized nuclear applications.",
Am: "Americium is used in some household smoke detectors.",
Cm: "Curium is a radioactive element named after Marie and Pierre Curie.",
Bk: "Berkelium is a synthetic radioactive element.",
Cf: "Californium is a synthetic radioactive element used in specialized neutron sources.",
Es: "Einsteinium is a synthetic element named after Albert Einstein.",
Fm: "Fermium is a synthetic radioactive element named after Enrico Fermi.",
Md: "Mendelevium is named after Dmitri Mendeleev.",
No: "Nobelium is named after Alfred Nobel.",
Lr: "Lawrencium is named after physicist Ernest Lawrence.",

Rf: "Rutherfordium is a synthetic radioactive element named after Ernest Rutherford.",
Db: "Dubnium is a synthetic element named after the Russian city of Dubna.",
Sg: "Seaborgium is named after chemist Glenn T. Seaborg.",
Bh: "Bohrium is named after physicist Niels Bohr.",
Hs: "Hassium is named after the German state of Hesse.",
Mt: "Meitnerium is named after physicist Lise Meitner.",
Ds: "Darmstadtium is named after the German city of Darmstadt.",
Rg: "Roentgenium is named after physicist Wilhelm Röntgen.",
Cn: "Copernicium is named after astronomer Nicolaus Copernicus.",
Nh: "Nihonium is named after Japan.",
Fl: "Flerovium is named after the Flerov Laboratory of Nuclear Reactions.",
Mc: "Moscovium is named after the Moscow region.",
Lv: "Livermorium is named after the Lawrence Livermore National Laboratory.",
Ts: "Tennessine is named after the U.S. state of Tennessee.",
Og: "Oganesson is named after physicist Yuri Oganessian."

};
